ALTER TABLE "platform_audit_log" ADD CONSTRAINT "platform_audit_log_actor_operator_id_platform_operators_id_fk" FOREIGN KEY ("actor_operator_id") REFERENCES "public"."platform_operators"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_deployment_specs" ADD CONSTRAINT "platform_deployment_specs_provisioning_run_id_platform_provisioning_runs_id_fk" FOREIGN KEY ("provisioning_run_id") REFERENCES "public"."platform_provisioning_runs"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_provisioning_runs" ADD CONSTRAINT "platform_provisioning_runs_created_by_platform_operators_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."platform_operators"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_provisioning_runs" ADD CONSTRAINT "platform_provisioning_runs_approved_by_platform_operators_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."platform_operators"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_provisioning_steps" ADD CONSTRAINT "platform_provisioning_steps_run_id_platform_provisioning_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."platform_provisioning_runs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform_deployment_specs" ADD CONSTRAINT "platform_specs_lifecycle_check" CHECK ("platform_deployment_specs"."lifecycle" IN ('preview', 'retired'));--> statement-breakpoint
ALTER TABLE "platform_operators" ADD CONSTRAINT "platform_operators_status_check" CHECK ("platform_operators"."status" IN ('active', 'disabled'));--> statement-breakpoint
ALTER TABLE "platform_provisioning_runs" ADD CONSTRAINT "platform_runs_status_check" CHECK ("platform_provisioning_runs"."status" IN ('planned', 'approved', 'applying', 'waiting_external', 'complete', 'failed'));--> statement-breakpoint
ALTER TABLE "platform_provisioning_runs" ADD CONSTRAINT "platform_runs_approval_check" CHECK (("platform_provisioning_runs"."approved_by" IS NULL AND "platform_provisioning_runs"."approved_at" IS NULL) OR ("platform_provisioning_runs"."approved_by" IS NOT NULL AND "platform_provisioning_runs"."approved_at" IS NOT NULL AND "platform_provisioning_runs"."approved_by" <> "platform_provisioning_runs"."created_by"));--> statement-breakpoint
ALTER TABLE "platform_provisioning_steps" ADD CONSTRAINT "platform_steps_execution_check" CHECK ("platform_provisioning_steps"."execution" IN ('automatic', 'external'));--> statement-breakpoint
ALTER TABLE "platform_provisioning_steps" ADD CONSTRAINT "platform_steps_status_check" CHECK ("platform_provisioning_steps"."status" IN ('pending', 'running', 'complete', 'waiting_external', 'failed'));